#!/usr/bin/env bash

# exit when script tries to use an undeclared variable
set -o nounset

die() {
    echo "$*"
    exit 1
}


main () {

    cd `dirname $0`/..
    ./dist/build/raycaster/raycaster

}

main "$@"

